### PR TITLE
Made a lot of changes please review 

### PR DESCRIPTION
**Pull request by Kickskii**
Updated Readme.md
Added build instructions
Changed a few functions so as to make the code buildable again
Removed website components(note to author: please feel free to keep them in if you need since i removed them only because i felt it more efficient to have everything on the markdown doc)
Added an icon to the EXE output
Built and released an exe as well as tested its functionality on the current nexus website

### CODE REVIEW

**Comment by parsiad** [comment]
I liked your changes, I was hoping we could massage and merge them. Why did you close the PR?

**Comment by Kickskii** [comment]
> I liked your changes, I was hoping we could massage and merge them. Why did you close the PR?

i apologize 
i genuinely wasnt expecting a response 
should i readd the website components and reopen the pull
since merging my existing fork will break your website

**Comment by Kickskii** [comment]
i also removed linting from the makefile cause it was giving the line count error and linting isnt exactly crucial to the makefile outputting an executable(the lint score was 9.2 idk if thats good enough but i couldnt do any better due to my lacking skills please forgive ;-;)

**Comment by parsiad** [comment]
Thanks for contributing; I incorporated some of your ideas (e.g., releasing the EXE on GitHub directly). I'm closing this in lieu of the new release.

**Pull request closed without merging**
